### ISSUE TITLE
Teste RemoteDataManager

### ISSUE THREAD

**Issue by amadeu01** [amadeu01/the-movie-db-client#6]
## Tarefas 

- [x] Estudar como posso injetar / como posso testar a classe que usa o Alamofire.
- [x] Implementar teste do `RemoteDataManager`

## Comentário 

>Então... pra vc conseguir testar o `RemoteDataManager` vc tem que alterar algumas coisas. Eu não conheço e não uso o Alamofire a fundo. Talvez ele ajude nisso. Mas, se vc quer testar unitariamente, o Alamofire teria que ser injetado nessa classe. Para na hora do teste vc conseguir mockar a request.
> @ronanrodrigo 

## Como posso fazer o teste?

Eu dei uma pesquisada e tem algumas libs que fazem stub do requisições HTTP, daí, consegue testar uma classe sem ter que injetar o alamofire.

- [Mockingjay](https://github.com/kylef/Mockingjay)

Um problema que achei com essa lib é que uso cartharge e eles não oferecem suporte para cartharge.
Poderia colocar manualmente a lib. (O que seria legal para aprender como poderia fazer isso, uma vez que nunca adicionei um framework manualmente, somente com cocoapod e cartharge)

- [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs)

Não me parece oferecer suporte para swift 4. Parece que o pessoal usa essa lib mais para obj-c.

- [Hippolyte](https://github.com/JanGorman/Hippolyte)

Me pareceu bem legal e promissor. Mas, não sei se funciona com alamofire.

## Post que podem ajudar

- [Network Stubbing options for XCTest and XCUITest in Swift](https://medium.com/xcblog/network-stubbing-options-for-xctest-and-xcuitest-in-swift-2e0dcce9a37d)

**Comment by amadeu01** [comment]
Tem esse cara aqui

- [Embassy](https://github.com/envoy/Embassy)

Mas, acho que ele é mais um tipo de servidor "fake" para daí fazer os request e daí ele vai responder simulando teu servidor normal.
Pareceu legal, mas acho que não é isso que estou procurando agora.

**Comment by ronanrodrigo** [comment]
No APP do Carrefour que eu trabalhei a gente estava usando o Mockinjay. E uma das prioridades nossa era tirar ele da jogada. Pq era uma coisa a mais que agente precisava se preocupar. E as features novas, a gente tava criando a nossa abstração do Alamofire, e com isso ficava mais simples de mockar. Além de ser bem mais fácil de trocar o Alamofire por outra lib no futuro. Se prender a uma lib, na maioria das vezes, não é bom.

**Comment by amadeu01** [comment]
Eu acho que vou derrubar essa issue com alguma lib dessa de fazer stub e depois vou fazer outra issue para criar uma abstração do alamofire.

Assim eu posso aprender duas vezes. 
1. Com uma lib dessa para fazer stub
2. Fazendo uma mudança de "depender de uma lib" para não depender a lib. Ou, fazer abstração do alamofire.

**Comment by ronanrodrigo** [comment]
- [Mocks, Fakes, Stubs and Dummies ](http://xunitpatterns.com/Mocks,%20Fakes,%20Stubs%20and%20Dummies.html)
- [Mock aren't Stubs](https://martinfowler.com/articles/mocksArentStubs.html)
- [When is it safe to Introduce Test Doubles](http://blog.thecodewhisperer.com/permalink/when-is-it-safe-to-introduce-test-doubles)
- [I Like Mocks, But I Distrust Spies](http://blog.thecodewhisperer.com/permalink/i-like-mocks)
- [Series](http://blog.thecodewhisperer.com/series)
- [TestDouble](https://www.martinfowler.com/bliki/TestDouble.html)

**Comment by amadeu01** [comment]
@ronanrodrigo terminei de ler sobre Facade.

Você tinha comentado que poderia ser uma boa ler sobre `Facade`. Você comentou no `MovieListLocalDataManager`. Mas, acredito que se aplica no `Alamofire` também no sentido de fazer um wrapper e criar um protocolo para falar com a lib que faz as requisições e daí abstrair as chamadas para o `Alamofire`. Dessa forma eu poderia mockar o meu protocolo da `Facade` e talvez até testar mais facilmente, tanto para o local (CoreData) quanto para o remoto (Alamofire)

**Comment by amadeu01** [comment]
Eu ainda quero seguir uma abordagem de fazert o stub, assim ganho essa experiência a mais.

**Comment by amadeu01** [comment]
@ronanrodrigo esse http://blog.thecodewhisperer.com/series é muito bom!!!

**Comment by amadeu01** [comment]
@ronanrodrigo  eu fiz mais um teste. Acho que dessa vez eu melhorei um pouco mais.

Quando puder, dar uma olhada e me diz se estou indo no caminho certo hehe 😄
